P#60741 / P#52107 Update allow sorting by all field + P#55975 improve sorting controls
onOfficeGmbH/oo-wp-plugin pull request #109
Opened 2021-08-20 10:00 UTC by hungnc89

fix #152

2021-08-20 15:22 UTC, jayay approved these changes

2021-10-18 15:03 UTC, jayay commented
@hungnc89 @kellyfa12 could you please check the tests?

2021-10-20 03:38 UTC, hungnc89 commented
> Thank you! Would you think it'd be possible to cover the new lines even better?

I will update more test

2021-11-09 08:23 UTC, jayay approved these changes

2021-11-11 07:11 UTC, michaelarnold-dev commented
@hungnc89 the testers identified some issues Test with version 2.17.0-3-gff1432c5 on https://wpptest.onofficeweb.com/:

1.) If "Sort by user selection" is unchecked, the old dropdown with fixed field selection is shown for "sort by", not the required new text field with selection of all fields.
2.) The text search does not find all active fields, e.g. year of construction (Baujahr) or floor (Etage) are missing.
3.) The order of the fields under "Popular" is not as in the specification screenshot. The field "Number of bathrooms" is missing in "Popular".
4.) In my case there are only 3 fields under "All", but there are many more fields active. All fields should be displayed under "All" that are not under "Popular".
5.) In order for the default sort to be current, the view must be reloaded first, if sort by user selection is on. Default sorting should be updated directly after "Save changes", if you have made changes in "Sort by". (We already deleted the browser cache but it did not help)

2021-11-11 16:36 UTC, jayay commented
@michaelarnold-dev commit ff1432c5 from the test is from Aug 20, a newer test zip would be more representative.

2021-12-06 16:05 UTC, jayay approved these changes

2022-02-07 08:14 UTC, jayay approved these changes

2022-02-22 15:39 UTC, jayay commented on plugin/Model/FormModelBuilder/FormModelBuilder.php
> +			$typeSupport = ['integer', 'float', 'varchar', 'text', 'date', 'datetime', 'boolean'];
This looks legit, but is it needed here? Feels like it should be added for both Fieldnames and FieldsCollectionBuilders, but in a separate project

2022-02-23 07:10 UTC, michaelarnold-dev commented
@hungnc89 Testing feedback: the errors are all still there. Could you please investigate again?

Version 2.21.2-12-g308568bf installed on https://1.wptest.onofficeweb.com/

2022-02-28 04:16 UTC, tang-hien-egs commented
> @hungnc89 Testing feedback: the errors are all still there. Could you please investigate again?
> 
> Version 2.21.2-12-g308568bf installed on https://1.wptest.onofficeweb.com/

@michaelarnold-dev , the errors fixed, i recorded in video link, can you check it ? , the link : https://files.fm/f/7cgwtdeve

2022-02-28 12:15 UTC, michaelarnold-dev commented
@tang-hien-egs 1.) If "Sort by user selection" is unchecked, the old dropdown with fixed field selection is shown for "sort by", not the required new text field with selection of all fields.
0:08 in the Video.

2.) The text search does not find all active fields, e.g. year of construction (Baujahr) or floor (Etage) are missing.
0:27 in the Video.

3.) The order of the fields under "Popular" is not as in the specification screenshot. The field "Number of bathrooms" is missing in "Popular".
0:27 in theVideo.

4.) In my case there are only 3 fields under "All", but there are many more fields active. All fields should be displayed under "All" that are not under "Popular".
cannot be seen in video

5.) In order for the default sort to be current, the view must be reloaded first, if sort by user selection is on. Default sorting should be updated directly after "Save changes", if you have made changes in "Sort by".
0:16 in the  Video.

2022-03-03 07:40 UTC, michaelarnold-dev commented
@tang-hien-egs @nglelinh Any updates here?

2022-03-03 08:00 UTC, tang-hien-egs commented
> @tang-hien-egs @nglelinh Any updates here?

@michaelarnold-dev , i tested in localhost, Record in tested local, in video like link : https://files.fm/f/pekvanp9p, i think you ask your tester should get code latest

2022-03-08 12:53 UTC, michaelarnold-dev commented
@tang-hien-egs According to our tester Robert Igelmund some bugs still exist. The errors 3-5 can be observed in that video. Could you please analyze?

https://user-images.githubusercontent.com/77264788/157241682-ac924a87-96f0-41a7-952e-a6548483998c.mp4

2022-03-09 07:08 UTC, michaelarnold-dev commented
@tang-hien-egs  Point 2.), 3.) and 4.) are not fixed for me. Can you record a video that shows that the bugs are fixed? The sorting of the fields under "Popular".That all fields are visible under "All". That fields "Year of construction" and "Floor" are found

2022-03-15 07:34 UTC, LongTrong-exe commented
@michaelarnold-dev Sorry for wasting your time, I will take this task from now.

2022-03-24 15:21 UTC, jayay submitted a review, later dismissed

2022-04-04 05:30 UTC, jayay approved these changes

2022-04-04 08:54 UTC, jmaas-onoffice approved these changes

2022-04-08 10:17 UTC, LongTrong-exe commented
@michaelarnold-dev 
I fixed both errors you said, but bug 1) doesn't seem to be mentioned in the requirements.
This's my test video:

https://user-images.githubusercontent.com/101325858/162416231-eb6a551c-cd1d-41f8-b27b-2b686caca5f0.mp4

2022-04-19 08:06 UTC, hungnc89 commented
- Tester tested
- Link video : https://files.fm/u/xcyvs5pgy#/view/4mtrq5ukg

2022-04-26 14:30 UTC, jayay submitted a review, later dismissed

2022-05-06 03:19 UTC, LongTrong-exe commented
@jmaas-onoffice Can you test this task?

2022-05-06 08:52 UTC, jmaas-onoffice approved these changes

2022-05-06 10:21 UTC, jmaas-onoffice approved these changes

2022-05-06 10:58 UTC, jmaas-onoffice requested changes
The requirements seem to not have been understandable enough. I will discuss this with Linh next Wednesday.

The issue:

We have two different types of sorting. A "simple" sort where you just choose how the estates are ordered and a "user" sort where you give the user a dropdown with which they can sort the estates. Which of the two modes is active is determined by the checkbox "Sort by user selection."

It seems that the "user" sort interface was copied to the "simple" sort. When the checkbox is not active, it should look like this:

![grafik](https://user-images.githubusercontent.com/90763364/167118412-562c109d-d6d7-47e4-930d-b54c507e66a2.png)

But in [3.1-32-gf25a2d75](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/109#issuecomment-1119470104) it looks like this:

![grafik](https://user-images.githubusercontent.com/90763364/167118785-219f0ed4-4e7f-4a8b-9f62-d81e0b9046ee.png)

I think it's easiest if I dicuss this with Linh next Wednesday. I think the requirements weren't very clear about this, so if we talk about it, we should be able to solve the problem. :)

2022-05-09 03:11 UTC, LongTrong-exe commented
@jmaas-onoffice When I received this task, the requirements error were not mentioned in the error report. So I thought it was okay, and I just fixed the bug that was reported by your tester.
By the way, can you resend me requirement?

2022-05-11 04:06 UTC, LongTrong-exe commented
> The requirements seem to not have been understandable enough. I will discuss this with Linh next Wednesday.
> 
> The issue:
> 
> We have two different types of sorting. A "simple" sort where you just choose how the estates are ordered and a "user" sort where you give the user a dropdown with which they can sort the estates. Which of the two modes is active is determined by the checkbox "Sort by user selection."
> 
> It seems that the "user" sort interface was copied to the "simple" sort. When the checkbox is not active, it should look like this:
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/167118412-562c109d-d6d7-47e4-930d-b54c507e66a2.png)
> 
> But in [3.1-32-gf25a2d75](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/109#issuecomment-1119470104) it looks like this:
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/167118785-219f0ed4-4e7f-4a8b-9f62-d81e0b9046ee.png)
> 
> I think it's easiest if I dicuss this with Linh next Wednesday. I think the requirements weren't very clear about this, so if we talk about it, we should be able to solve the problem. :)



> The requirements seem to not have been understandable enough. I will discuss this with Linh next Wednesday.
> 
> The issue:
> 
> We have two different types of sorting. A "simple" sort where you just choose how the estates are ordered and a "user" sort where you give the user a dropdown with which they can sort the estates. Which of the two modes is active is determined by the checkbox "Sort by user selection."
> 
> It seems that the "user" sort interface was copied to the "simple" sort. When the checkbox is not active, it should look like this:
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/167118412-562c109d-d6d7-47e4-930d-b54c507e66a2.png)
> 
> But in [3.1-32-gf25a2d75](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/109#issuecomment-1119470104) it looks like this:
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/167118785-219f0ed4-4e7f-4a8b-9f62-d81e0b9046ee.png)
> 
> I think it's easiest if I dicuss this with Linh next Wednesday. I think the requirements weren't very clear about this, so if we talk about it, we should be able to solve the problem. :)

@jmaas-onoffice I just checked this function on master brand and got what you mean. I think it's not difficult to understand.
If you have any problem with the requirements, please discuss with Linh.

2022-05-11 04:50 UTC, LongTrong-exe commented
Is this okay?

https://user-images.githubusercontent.com/101325858/167771368-7722aa05-18cd-4aaa-bd67-422f7fbc15c8.mp4

2022-05-11 11:45 UTC, jmaas-onoffice commented
@LongTrong-exe Is the code from [your video](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/109#issuecomment-1123183525) in this PR? Because when I install [3.1-32-gf25a2d75](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/109#issuecomment-1119470104) it doesn't work like in your video, as you can see on https://2.wptest.onofficeweb.com/.

2022-05-11 12:23 UTC, LongTrong-exe commented
@jmaas-onoffice New code is still in my local PC, I will push it tomorrow. I need to test it more for sure.

2022-05-11 12:35 UTC, jmaas-onoffice commented
Ah, ok, now I understand. Awesome, then just request a review when it's ready. Thanks! :)

2022-05-12 09:08 UTC, jmaas-onoffice approved these changes

2022-05-12 11:08 UTC, jmaas-onoffice requested changes
1. In the simple sort mode (not the user sort mode), you don't have access to all fields when sorting.
    ![grafik](https://user-images.githubusercontent.com/90763364/168056856-adec06ac-285c-44d7-9a0f-1644cb84a7d2.png)
2. You can currently select unsupported fields. The highlighted field is a separator:
    ![grafik](https://user-images.githubusercontent.com/90763364/168057370-17aad810-714a-489f-9eab-2a885cd09c6a.png)
    Only valid field types should be selectable. Which fields are valid is defined by #168.

2022-05-13 04:40 UTC, LongTrong-exe commented
@jmaas-onoffice I'm filtering the field by these types:
![image](https://user-images.githubusercontent.com/101325858/168212275-b5e960db-ccac-43bb-bcd5-4d26eb6ed4b9.png)
So I think field "---------" you are talking about has a problem with its label, not its type

2022-05-13 10:32 UTC, jmaas-onoffice commented
@LongTrong-exe Good point. Unfortunately it seems that I can actually select a separator:

![grafik](https://user-images.githubusercontent.com/90763364/168265698-e6db2eab-d5b0-44dd-8629-ef4efad301f8.png)

I have updated https://1.wptest.onofficeweb.com/ and here is a screenshot of the configured fields:

![grafik](https://user-images.githubusercontent.com/90763364/168265770-de2092db-cf65-401c-a476-117c5c8b2ce1.png)

I shouldn't be able to select for example "BLACK HINT", but I can:

![grafik](https://user-images.githubusercontent.com/90763364/168265846-1b0fa603-2ce8-4c2f-a47b-f8ff3ef6645f.png)

So it seems that the fields are not filtered correctly. Could you fix it?

2022-05-13 10:32 UTC, jmaas-onoffice commented
Also, should we merge this with #175, since they might conflict?

2022-05-13 11:09 UTC, LongTrong-exe commented
@jmaas-onoffice This is weird, I think there is a problem with your API. This is the response of "BLACK HINT" field, as you can see, its type is "text", even though its type in onoffice is "Schwarzer Hinweis".
![image](https://user-images.githubusercontent.com/101325858/168269490-821ed8a7-9389-42bc-870c-c9b508a3bd33.png)

2022-05-13 11:38 UTC, jmaas-onoffice commented
Yes, I had the same issue. You have to set the flag `realDataTypes` (https://apidoc.onoffice.de/actions/informationen-abfragen/feldkonfiguration/).

2022-05-16 08:30 UTC, jmaas-onoffice approved these changes

2022-05-16 08:43 UTC, jmaas-onoffice requested changes
1. When you activate the random sort, the checkbox for "Sort by user selection" gets deselected but the fields below are still the ones for user selection.

    https://user-images.githubusercontent.com/90763364/168553189-2e1828e0-b6ae-4a75-9536-4b598783c0d5.mp4

   When random sort is selected, the fields above should only be deactivated. The checkbox state should not be changed.

2. I'm not sure if this is in the original requirements, but in the user selection sort after adding criteria to "Sort by", I can't immediately select them in "Standard sort". I need to save the page, before I can select them.

   https://user-images.githubusercontent.com/90763364/168553527-f31ee0d4-a8b0-4748-aca1-40a4f1a4c2ba.mp4

   Could you make it so that when I add search criteria to "Sort by" that they are immediately selectable in "Standard sort"?

2022-05-16 09:07 UTC, LongTrong-exe commented
@jmaas-onoffice Is this what you want? This is on my local PC.

https://user-images.githubusercontent.com/101325858/168558548-e27458d3-db11-4bdb-82af-eb7c2f5e6ff6.mp4

2022-05-16 09:32 UTC, LongTrong-exe commented
@jmaas-onoffice Is this what you want? This is on my local PC.

https://user-images.githubusercontent.com/101325858/168563018-2e01fa48-a6ba-4702-ba9a-e431fe66ce18.mp4

2022-05-17 07:00 UTC, jmaas-onoffice approved these changes

2022-05-17 07:29 UTC, jmaas-onoffice requested changes
I've found a small issue when updating:

1. In version 3.1 make an estate list and set its ordering to "Random".
2. Update to the newest code.
3. The "Random" checkbox is correctly set, but the "Sort by User Selection" checkbox is not disabled.

    https://user-images.githubusercontent.com/90763364/168754262-640cfbd0-13cc-47df-90ff-3e3db11daf33.mp4

Apart from that it looks very good! I think we will be finally able to merge this soon!

2022-05-17 08:11 UTC, LongTrong-exe commented
@jmaas-onoffice Thanks, you are such a great tester. I fixed it.

2022-05-17 11:58 UTC, jmaas-onoffice submitted a review, later dismissed

2022-05-17 12:09 UTC, jmaas-onoffice commented
@LongTrong-exe I forgot to ask in my last comment: This was not in the requirements, but for address lists you can still only select a fixed set of sorting criteria. How much time would it take to allow selecting any field for sorting address lists as well?

2022-05-18 02:08 UTC, LongTrong-exe commented
> @LongTrong-exe I forgot to ask in my last comment: This was not in the requirements, but for address lists you can still only select a fixed set of sorting criteria. How much time would it take to allow selecting any field for sorting address lists as well?

@jmaas-onoffice I think it could take about three to five days, but you should create a new task for it.

2022-05-18 07:00 UTC, jmaas-onoffice commented
@LongTrong-exe Ok, then let's leave it for now. Address lists are rarely used, so I don't want to put too much effort there.

Can we merge this with #175? I think it makes sense to release both together.

2022-05-19 07:38 UTC, LongTrong-exe commented
@jmaas-onoffice I merged them, I think it looks good, can you test it?

2022-05-19 08:55 UTC, jmaas-onoffice approved these changes

2022-05-19 09:35 UTC, jmaas-onoffice requested changes
I found a small bug:

It seems that there is a problem with "Random sort". I think when the backend says "Random sort" is selected, it actually still has "Default sort" selected.

There are a few ways that this causes problems:

1. When I create a new estate list, the backend shows "Random sort". It should show select "Default sort". A few observations:
    - When I save this new list without changes (i.e. with "Random sort"), and then go to the page in the frontend with the shortcode and reload the page, the order never changes. If "Random sort" was active, the order of the estates should change on every page load.
    - I can set the sorting to "Default sort", change the settings and save, and they will be active. E.g. I can set "Sort order" to "Descending" and in the frontend the order flips. But when I then try to select "Random sort" and save, the order in the frontend is the same as before and it doesn't change when I reload the page.
2. If in v3.1 I have a list set to "Default sort" (i.e. "Sort by user selection" and "Random sort" are not checked) and then upgrade to the current code, the backend will show "Random sort" but the frontend will be correctly sorted with the settings from before the update. Also, when in the backend you switch to "Default sort", it shows the correct settings (e.g. if before the update I selected "Number of rooms" for "Sort by", it now also shows "Number of rooms" correctly).

Overall, I think that this is a GUI issue in the estate list settings.

2022-05-19 10:25 UTC, LongTrong-exe commented
This's my test video:

https://user-images.githubusercontent.com/101325858/169272379-84359ae1-80d4-4dc9-95a6-fd2bad7549f7.mp4

2022-05-19 10:45 UTC, LongTrong-exe commented
> 2. If in v3.1 I have a list set to "Default sort" (i.e. "Sort by user selection" and "Random sort" are not checked) and then upgrade to the current code, the backend will show "Random sort"

Thank you, but I can't reproduce (2.) "Default sort" list is still "Default sort" when I update to the new version.

2022-05-19 11:42 UTC, jmaas-onoffice commented
Maybe you've fixed it. I think both problems have the same cause. I'll test it. 👍

2022-05-19 11:42 UTC, jmaas-onoffice approved these changes

2022-05-19 12:14 UTC, jmaas-onoffice requested changes
Unfortunately, I still have the second bug. Here is how I can reproduce it:

1. In v3.1 create a new estate list. Just add a name, do not change the settings.
    ![grafik](https://user-images.githubusercontent.com/90763364/169289003-186c7412-706a-43b8-96c2-8067a8336042.png)
2. Update to [3.1-72-g09b8e217](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/109/#issuecomment-1131584862).
3. Open the settings of the estate list. The sorting is set to "Random sort".
    ![grafik](https://user-images.githubusercontent.com/90763364/169290606-34810ca9-ecfa-4de1-9f75-87f697f7c1c2.png)

If you still can't reproduce this, I will set up a test instance when one is free.

2022-05-20 02:14 UTC, LongTrong-exe commented
@jmaas-onoffice yes, I understand what you say. There is a backward compatibility problem when changing from checkbox to select type. I'll fix it.

2022-05-20 03:41 UTC, LongTrong-exe commented
https://user-images.githubusercontent.com/101325858/169446014-b8536a36-3b34-412d-a335-db75fdf27d39.mp4

2022-05-20 06:51 UTC, jmaas-onoffice approved these changes

2022-05-20 07:28 UTC, merged