P#50177 Display Links, Ogulo-Links, Objekt-Links in the detail view
onOfficeGmbH/oo-wp-plugin pull request #126
Opened 2021-10-22 07:46 UTC by hungnc89

2021-11-01 04:06 UTC, hungnc89 commented on plugin/EstateDetail.php
> +				$player = '<iframe width="' . $newOptions['width'] . '" height="' . $newOptions['height'] . '" src="' . $properties['url'] .'" style="border: none"
@jayay I tried to improve the test for EstateDetail. But it is very difficult to continue. This job will take a long time

2021-11-12 07:45 UTC, michaelarnold-dev commented
@tung-le-esg Could you please check this?

2022-01-12 10:39 UTC, hungnc89 commented
@jayay could you please continue to review this PR?

2022-01-24 02:46 UTC, hungnc89 commented
@jayay could you please review this PR?

2022-01-31 07:31 UTC, jayay commented on css/onoffice_defaultview.css
> +.oo-video .player-title {
Do we break existing layouts with this?

2022-01-31 07:39 UTC, jayay commented on plugin/Types/LinksTypes.php
> +	private static $_linkTypes = [
Please move immutable data into a `const`.

2022-01-31 08:15 UTC, jayay commented on css/onoffice_defaultview.css
> +.oo-video .player-title {
Same problem as https://github.com/onOfficeGmbH/oo-wp-plugin/pull/106#issuecomment-1025476719

What do you think about the possible solution?

2022-02-10 07:57 UTC, hoangdoegs commented
@jayay Could you please review this PR?

2022-02-15 14:33 UTC, jayay submitted a review, later dismissed

2022-03-31 13:36 UTC, jayay submitted a review, later dismissed

2022-04-19 13:59 UTC, michaelarnold-dev commented
Testing feedback:
Test with version 2.21.2-15-gb90e1685 on https://1.wptest.onofficeweb.com/7-2/111-schnapper/. See also the attached screenshots.

1.) Mode link: For movie links, the title is missing.
2.) Titles of links are always written in capital letters, although in enterprise are written in small letters. This has not been a requirement. They should be written like in enterprise.
3.) Mode embedded: The title of movie link and ogulo link is bigger than the other titles. Titles should have uniform size.

2022-04-20 10:34 UTC, jmaas-onoffice requested changes
See the requested changes in https://github.com/onOfficeGmbH/oo-wp-plugin/pull/126#issuecomment-1102692614.

2022-05-05 10:02 UTC, hungnc89 commented
- Tester tested
- Video

https://user-images.githubusercontent.com/72601287/166902026-c22a406b-e60e-42e8-8816-f6d18346f4a4.mp4

2022-05-09 07:20 UTC, tang-hien-egs commented
@jmaas-onoffice , i fixed PR, please check it help me !

2022-05-09 10:52 UTC, jmaas-onoffice approved these changes

2022-05-10 11:16 UTC, jmaas-onoffice commented
Works great. :)

I asked a colleague for feedback and they asked for some slight changes to the template. So I just implemented them myself.

2022-05-10 11:16 UTC, jmaas-onoffice submitted a review, later dismissed

2022-05-10 11:39 UTC, jmaas-onoffice approved these changes

2022-05-10 11:41 UTC, merged