P#55975-improve-sorting-controls-17550
onOfficeGmbH/oo-wp-plugin pull request #131
Opened 2021-11-05 03:03 UTC by hungnc89

- add box "Sorting" on admin when setting estate and address
- update view select sorting type on estate (jquery)

2021-11-05 07:02 UTC, jayay requested changes
Please see my other comments. The tests need to be fixed.

2021-11-05 07:02 UTC, jayay commented on plugin/Installer/DatabaseChanges.php
> +			`sortByUserDefinedDirection` ENUM('0','1') NOT NULL DEFAULT '0' COMMENT 'Formulierung der Sortierrichtung: 0 means highestFirst/lowestFirt, 1 means descending/ascending',`page_shortcode` tinytext
This also leads to a SQL syntax error. I wonder if `dbDelta()` accepts it with a newline-character. See https://github.com/onOfficeGmbH/oo-wp-plugin/runs/4113056535#step:9:14

2021-11-12 07:46 UTC, michaelarnold-dev commented
@tung-le-esg Could you please check the tests?

2021-11-18 02:11 UTC, closed without merging

2021-11-22 06:29 UTC, vu-vuong-esg commented
> @tung-le-esg Could you please check the tests?

We have closed this PR and created the new one in here https://github.com/onOfficeGmbH/oo-wp-plugin/pull/137