P#56183 Optimize columns on list views for forms estates and addresses
onOfficeGmbH/oo-wp-plugin pull request #139
Opened 2021-11-17 09:23 UTC by tung-le-esg

P#56183 Optimize columns on list views for forms estates and addresses

2021-12-22 16:46 UTC, jayay commented on tests/TestClassDatabaseChanges.php
> +		$this->assertGreaterThanOrEqual(count($uniqueCreateQueries), count($uniqueDropQueries));
How can more tables be dropped than created?

2021-12-28 13:02 UTC, jayay requested changes

2021-12-28 13:02 UTC, jayay commented on plugin/Gui/Table/EstateListTable.php
> +		foreach ($listRecord as &$record)
An array of new records would be cleaner than `&`.

2021-12-28 13:02 UTC, jayay commented on plugin/Installer/DatabaseChanges.php
> +			`page_shortcode` tinytext NOT NULL,
isn't this duplicate information? This is the name with some constant string left and right. Totally reproducible.

2022-01-07 02:44 UTC, vu-vuong-esg commented on plugin/Controller/DetailViewPostSaveController.php
> +				$pRecordReadListView->updateColumnPageShortCode($pageID,$view->$primaKey,$tableName,$column);
no, because update database use primakey in tables

2022-01-07 14:24 UTC, jayay requested changes

2022-01-07 14:24 UTC, jayay commented on plugin/Gui/Table/EstateListTable.php
> +	private function handleRecord($listRecord)
This is still open

2022-01-07 14:24 UTC, jayay commented on plugin/Gui/Table/EstateListTable.php
> +					if (!empty($page))
this is still open, too

2022-01-31 10:46 UTC, jayay approved these changes

2022-02-21 19:17 UTC, jayay approved these changes

2022-02-28 14:39 UTC, michaelarnold-dev commented
@hungnc89 test feedback "Test with version 2.21.4-13-gd93dcbf6 installed on https://wpptest.onofficeweb.com/. See also the attached video.

https://user-images.githubusercontent.com/77264788/156001923-c224a12f-3b0f-404f-bc81-1a7eaf75fd39.mp4


1.) After installing the project code all previously created lists, forms etc. are gone. When switching back to another code, they are there again.
2.) After saving a list or a form it does not appear in list view.
3.) The names from the screenshots are used everywhere. But the names from the text in the requirements are the relevant ones. Only for forms instead of "List name" is better "Form name"."

2022-03-02 04:20 UTC, tang-hien-egs commented
> @hungnc89 test feedback "Test with version 2.21.4-13-gd93dcbf6 installed on https://wpptest.onofficeweb.com/. See also the attached video.
> 
>  Errors.mp4 
> 1.) After installing the project code all previously created lists, forms etc. are gone. When switching back to another code, they are there again. 2.) After saving a list or a form it does not appear in list view. 3.) The names from the screenshots are used everywhere. But the names from the text in the requirements are the relevant ones. Only for forms instead of "List name" is better "Form name"."

@michaelarnold-dev , i tested in localhost oki, i recorded in video like link : https://files.fm/f/87gz62b92, can you check and upgrade db_version ?

2022-03-08 06:52 UTC, michaelarnold-dev commented
@tang-hien-egs Robert said that 3) is still open. He asks you to consider these values /fields

1.1) Add the following columns to the estate list overview:
- List name
- Selected filter
- Template
- List type
- Shortcode
- Pages using the shortcode

1.2) For the forms:
- Form name
- Recipient e-mail address
- Template
- Form type
- Shortcode
- Pages using the shortcode

1.3) For addresses:
- List name
- Selected filter
- Template
- List type
- Shortcode
- Pages using the shortcode

2022-03-10 02:12 UTC, tang-hien-egs commented
> @tang-hien-egs Robert said that 3) is still open. He asks you to consider these values /fields
> 
> 1.1) Add the following columns to the estate list overview:
> 
> * List name
> * Selected filter
> * Template
> * List type
> * Shortcode
> * Pages using the shortcode
> 
> 1.2) For the forms:
> 
> * Form name
> * Recipient e-mail address
> * Template
> * Form type
> * Shortcode
> * Pages using the shortcode
> 
> 1.3) For addresses:
> 
> * List name
> * Selected filter
> * Template
> * List type
> * Shortcode
> * Pages using the shortcode

@michaelarnold-dev , i fixed it, can you check it ?

2022-03-10 08:07 UTC, tang-hien-egs commented
@michaelarnold-dev , i tested local and record video like link : https://files.fm/f/yqk2a5zwr

2022-03-10 16:23 UTC, tang-hien-egs commented
> @tang-hien-egs could you please clean up the code from your last commit?

@jayay  i fixed it and fixed conflict, can you check PR help me ?

2022-03-11 10:08 UTC, jayay approved these changes

2022-03-15 08:05 UTC, merged