P#60739 Remove unsupported data types - Data types still visible in some lists
onOfficeGmbH/oo-wp-plugin pull request #168
Opened 2022-01-11 04:23 UTC by vu-vuong-esg

P#60739 Remove unsupported data types - Data types still visible in some lists

2022-01-24 02:52 UTC, hungnc89 commented
@jayay could you please review this PR?

2022-03-29 08:08 UTC, tang-hien-egs commented
@jayay could you please review this PR?

2022-04-06 07:43 UTC, jayay commented on plugin/Field/Collection/FieldLoaderGeneric.php
> +			$listTypeUnSupported = ['user', 'date', 'redhint', 'blackhint', 'dividingline'];
Did you check which one is correct? _datei_ is German for _file_, which is what is supposed to be removed in this project.

2022-04-06 07:44 UTC, jayay commented on plugin/Field/Collection/FieldLoaderGeneric.php
> +			$listTypeUnSupported = ['user', 'date', 'redhint', 'blackhint', 'dividingline'];
This also applies to the other changes of the commit

2022-04-07 12:00 UTC, jayay approved these changes

2022-04-21 08:52 UTC, jayay submitted a review, later dismissed

2022-04-28 09:07 UTC, tang-hien-egs commented
@jmaas-onoffice , Jakob approved , could you check PR help me ?

2022-04-29 11:14 UTC, jmaas-onoffice commented
This is still in the "old" workflow (marked with the `feedback-jakob` label), so the testers will have a look.

I'm currently busy with the other tickets.

2022-05-04 02:25 UTC, tang-hien-egs commented
> 
sorry, i will ask Michael check it help me !

2022-05-04 02:26 UTC, tang-hien-egs commented
@michaelarnold-dev , could you check PR help me ?

2022-05-06 03:24 UTC, tang-hien-egs commented
@michaelarnold-dev , please check PR help me ?

2022-05-09 11:51 UTC, michaelarnold-dev commented
@tang-hien-egs according to Robert Igelmund the code still doesn't work as expacted. Here you can find a screenshot
![data_types_still_visible](https://user-images.githubusercontent.com/77264788/167404240-aa9396f8-e160-42d2-a7ac-5832a84892e3.png)

2022-05-10 04:00 UTC, tang-hien-egs commented
> @tang-hien-egs according to Robert Igelmund the code still doesn't work as expacted. Here you can find a screenshot ![data_types_still_visible](https://user-images.githubusercontent.com/77264788/167404240-aa9396f8-e160-42d2-a7ac-5832a84892e3.png)

@michaelarnold-dev , could you give me information about serve testing, because i test in local is Ok 
![img_test_60739](https://user-images.githubusercontent.com/95266110/167540041-64128318-c1c1-4059-b487-2519360b2346.png)
?

2022-05-11 13:46 UTC, jmaas-onoffice approved these changes

2022-05-11 14:03 UTC, jmaas-onoffice requested changes
Could you fix the failing unit test? I merged `master` into here and now some of the tests are failing.

2022-05-12 00:42 UTC, vu-vuong-esg commented
> Could you fix the failing unit test? I merged `master` into here and now some of the tests are failing.

i fixed errors, please check PR help me !

2022-05-12 06:29 UTC, jmaas-onoffice approved these changes

2022-05-12 06:49 UTC, jmaas-onoffice requested changes
When I add some of those unsupported fields to a list in version 3.1 and then update, the fields stay in the estate list. They should be removed.

Note that they are removed from the fields that you can select on the left, but they remain in the list on the right.

2022-05-13 07:41 UTC, tang-hien-egs commented
@jmaas-onoffice : is this your mean like image ?
![JOHANNESS_1](https://user-images.githubusercontent.com/95266110/168235210-a0401f24-512d-4259-b7b0-e1aaea40bb77.jpg)


![JOHANNESS_222](https://user-images.githubusercontent.com/95266110/168235255-c7b40301-a534-47f7-8792-955841f2b09f.jpg)

2022-05-13 12:04 UTC, jmaas-onoffice commented
That's the correct part of the interface, but I don't know if it is clear what should happen. So here's an example.

Before the update, on version 3.1, I can add the following fields. (The first two are normal fields, the others are of types that this PR should remove.)

![grafik](https://user-images.githubusercontent.com/90763364/168278308-04fabad3-496b-4a1a-abf4-d97ef05ee21d.png)

Now I update to [3.1-21-g03bd2867](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/168#issuecomment-1124581277). As you can see in the following image, the fields are gone from the left, but they are still on the right.

![grafik](https://user-images.githubusercontent.com/90763364/168279022-d8ed4d18-09c7-4dac-9bbd-c69c66cc5b87.png)

When I update, the fields on the right should be removed so that it looks like this:

![grafik](https://user-images.githubusercontent.com/90763364/168279336-bc10953a-14e7-4627-a3b3-f2d4f2a9fdce.png)

2022-05-18 06:07 UTC, tang-hien-egs commented
> That's the correct part of the interface, but I don't know if it is clear what should happen. So here's an example.
> 
> Before the update, on version 3.1, I can add the following fields. (The first two are normal fields, the others are of types that this PR should remove.)
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/168278308-04fabad3-496b-4a1a-abf4-d97ef05ee21d.png)
> 
> Now I update to [3.1-21-g03bd2867](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/168#issuecomment-1124581277). As you can see in the following image, the fields are gone from the left, but they are still on the right.
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/168279022-d8ed4d18-09c7-4dac-9bbd-c69c66cc5b87.png)
> 
> When I update, the fields on the right should be removed so that it looks like this:
> 
> ![grafik](https://user-images.githubusercontent.com/90763364/168279336-bc10953a-14e7-4627-a3b3-f2d4f2a9fdce.png)

yes, i clean requiremet , i will update it !

2022-05-31 06:49 UTC, yeneastgate commented
Convert code to this pull request #258

2022-05-31 06:49 UTC, closed without merging