P#65163 [WP-Plugin] Detail page leads to error when it has a parent page
onOfficeGmbH/oo-wp-plugin pull request #182
Opened 2022-02-18 02:24 UTC by hungnc89

2022-02-21 19:24 UTC, jayay commented on plugin/EstateList.php
> +	private $_isOverride_DataView = false;
I was hoping this wouldn't be necessary, especially it only exists for the tests

2022-02-21 19:25 UTC, jayay commented on plugin/Utility/Redirector.php
> +		return true;
Is the return value necessary?

2022-02-21 19:26 UTC, jayay reviewed
I had two things annotated

2022-03-04 13:51 UTC, jayay submitted a review, later dismissed

2022-03-25 14:20 UTC, michaelarnold-dev commented
@hungnc89 
Version 2.21.7-18-gfcdf53e4 imstalled on https://wpptest.onofficeweb.com/:

Some estate detail views do not load. It comes "Page not available". See video. Cause unclear.
--> All detail views displayed in the list should open correctly

https://user-images.githubusercontent.com/77264788/160138457-45be570e-879f-4322-9d02-34955eb42ba5.mp4

.

2022-03-29 09:28 UTC, LongTrong-exe commented
@michaelarnold-dev oh sorry, let me update this brand. your bug you said is a old feature, It has been updated in the new version.

2022-04-04 09:49 UTC, jayay approved these changes

2022-04-04 10:00 UTC, jayay submitted a review, later dismissed

2022-04-07 13:18 UTC, jmaas-onoffice requested changes
The bug with the parent page is fixed, thanks!

Unfortunately there still is a bug in [version 2.22.5-21-ge0af7dd8]():

When I "break" the title, the redirection fails with the error message `Cannot modify header information - headers already sent`.

https://user-images.githubusercontent.com/90763364/161999964-d92a8592-b117-42b9-a0c3-9c9328518178.mp4

I have noticed that this error does not occur with the theme "Twenty Twenty-Two". It does occurr with the theme "Neve". I have not tested other themes. I have set up "Neve" on https://2.wptest.onofficeweb.com/, and you can use that server for testing.

Could you please fix this?):

2022-04-12 03:36 UTC, LongTrong-exe commented
@jmaas-onoffice I fixed the bug, this's my test video:

https://user-images.githubusercontent.com/101325858/162874998-950e1328-b65b-420e-8a26-39379f5e84a1.mp4

2022-04-12 09:20 UTC, jmaas-onoffice approved these changes

2022-04-12 13:18 UTC, merged