P#69791: Migrate show reference estate setting properly
onOfficeGmbH/oo-wp-plugin pull request #217
Opened 2022-04-19 02:03 UTC by hungnc89

2022-04-19 08:19 UTC, LongTrong-exe commented on js/onoffice-reference-estate-select.js
>      const valueSelect = 'reference';
I think name of the $valueSelect const should be more precise

2022-04-19 08:19 UTC, LongTrong-exe commented on plugin/Installer/DatabaseChanges.php
> +	public function updateShowReferenceEstate()
This function name should also be more precise

2022-04-27 02:10 UTC, LongTrong-exe submitted a review, later dismissed

2022-04-28 07:31 UTC, hungnc89 commented
- Tester tested
- Video

https://user-images.githubusercontent.com/72601287/165700624-5e6a7423-32b6-4646-bc95-4102d52a19a6.mp4

2022-05-11 12:52 UTC, jmaas-onoffice approved these changes

2022-05-11 13:13 UTC, jmaas-onoffice requested changes

2022-05-11 13:13 UTC, jmaas-onoffice commented on plugin/Installer/DatabaseChanges.php
> +				WHERE `list_type` = 'reference'";
This was a bit ambiguous in the requirements, but this should be set for all list types.

The reason is that previously, reference estates were always shown, for all list types. So for backwards compatibility, we need to keep showing reference estates.

2022-05-16 07:21 UTC, jmaas-onoffice approved these changes

2022-05-16 07:24 UTC, jmaas-onoffice approved these changes

2022-05-16 07:48 UTC, merged