form changes: added Placeholder, Labels, CSS
onOfficeGmbH/oo-wp-plugin pull request #28
Opened 2020-11-23 10:13 UTC by miauzjpg

added placeholder to inputs, label tags, two column CSS, nicer success and error messages

2020-11-30 15:00 UTC, jayay commented
Your change makes the forms a lot prettier. However, it is unclear to me whether a `placeholder` is wanted for `<input>`s. It makes things look odd to me and I can't be the only one.

![image](https://user-images.githubusercontent.com/2384578/100625639-112e8500-3325-11eb-9c9c-ba818ec87627.png)

2020-12-01 17:37 UTC, jayay requested changes

2020-12-07 09:16 UTC, miauzjpg commented on templates.dist/form/applicantform.php
> +		$line = "<label for=".$input.">". $pForm->getFieldLabel( $input ).$addition.':</label>';
ok, done.

2020-12-07 09:16 UTC, miauzjpg commented on templates.dist/form/applicantform.php
> +	<h2>Ihre Kontaktdaten</h2>
added translation

2020-12-07 09:16 UTC, miauzjpg commented on templates.dist/form/defaultform.php
> +			echo "<label for=".$input.">". $pForm->getFieldLabel($input).$addition.": </label>";
ok, done.

2020-12-07 12:13 UTC, miauzjpg commented
> Your change makes the forms a lot prettier. However, it is unclear to me whether a `placeholder` is wanted for `<input>`s. It makes things look odd to me and I can't be the only one.
> 
> ![image](https://user-images.githubusercontent.com/2384578/100625639-112e8500-3325-11eb-9c9c-ba818ec87627.png)

First we want to display Placeholder and in the next steps maybe hints.

2021-02-08 15:28 UTC, jayay commented
If you feel like this should be done, please create a task so that it becomes an official project. It is too risky for me to just accept "random" changes.

2021-02-08 15:28 UTC, closed without merging