P#39193-Replace text domain 'onoffice' to 'onoffice-for-wp-websites'
onOfficeGmbH/oo-wp-plugin pull request #30
Opened 2020-11-24 02:11 UTC by nglelinh

P#39193 WP-Plugin und Language-Packs

2020-11-30 14:15 UTC, jayay requested changes
Most of this is good, but it's missing the fixes I made in [830ad22](https://github.com/onOfficeGmbH/oo-wp-plugin/commit/830ad22b2853ba962f58a5f698cfa8f5d74bb32c). The `.pot` file should be regenerated by running `make pot` (requires GNU Make) and the `.po` files should be updated.

2020-11-30 14:15 UTC, jayay commented on plugin/Gui/AdminPageBase.php
> +		echo '<h1 class="wp-heading-inline">'.esc_html__('onoffice-for-wp-websites', 'onoffice-for-wp-websites');
This doesn't look right to me

2020-11-30 14:15 UTC, jayay commented on plugin/Gui/AdminPageEstateUnitList.php
> +		echo '<h1 class="wp-heading-inline">'.esc_html__('onoffice-for-wp-websites', 'onoffice-for-wp-websites');
The first parameter needs to stay

2020-12-01 10:34 UTC, jayay commented on tests/WP_UnitTest_Localized.php
> +            load_textdomain('onoffice-for-wp-websites', ONOFFICE_PLUGIN_DIR.'/languages/onoffice-for-wp-websites-'.$newLocale.'.mo');
this is a tab/space mix

2020-12-02 18:21 UTC, jayay commented
Most translations get loaded, except for a couple and I couldn't find out why. @nglelinh  would you mind having a look? Here's a screenshot. _Show 2 matches_ should be translated as well, but isn't.
![image](https://user-images.githubusercontent.com/2384578/100914124-eda93d00-34d2-11eb-995f-d9cdca8b6eef.png)

In addition to that, I don't think the code to load the user defined translations is correct. Would you please try out this?

```diff
--- a/plugin.php
+++ b/plugin.php
@@ -108,15 +108,16 @@ add_action('admin_init', [$pAdminViewController, 'add_ajax_actions']);
 add_action('admin_init', [CaptchaDataChecker::class, 'addHook']);

 add_action('plugins_loaded', function() {
-       load_plugin_textdomain('onoffice', false, basename(ONOFFICE_PLUGIN_DIR).'/languages');
-       load_plugin_textdomain('onoffice-for-wp-websites', false, basename(ONOFFICE_PLUGIN_DIR) . '/languages');
+       load_plugin_textdomain('onoffice-for-wp-websites', false, basename(ONOFFICE_PLUGIN_DIR) . '/languages/onoffice-for-wp-websites');
+       // Check 'onoffice-personalized' Folder exists
+       $onofficePersonalizedFolder = plugin_dir_path(__DIR__) . 'onoffice-personalized/languages';
+       if (is_dir($onofficePersonalizedFolder)) {
+               load_plugin_textdomain('onoffice', false, $onofficePersonalizedFolder);
+       } else {
+               load_plugin_textdomain('onoffice', false, basename(ONOFFICE_PLUGIN_DIR).'/languages');
+       }
 });

-// Check 'onoffice-personalized' Folder exists
-$onofficePersonalizedFolder = plugin_dir_path(__DIR__) . 'onoffice-personalized';
-if (is_dir($onofficePersonalizedFolder)) {
-       load_plugin_textdomain('onoffice', false, basename(ONOFFICE_PLUGIN_DIR) . '/languages');
-}

 // "Settings" link in plugins list
 add_filter('plugin_action_links_'.plugin_basename(__FILE__), [$pAdminViewController, 'pluginSettingsLink']);
```

2020-12-02 18:41 UTC, jayay commented
In regards to
> _Show 2 matches_ should be translated as well, but isn't.

I've updated that exact translation on the WP translations platform as it might be possible that's the one and only source for that text domain. I'll have a closer look at that tomorrow.

2020-12-03 06:33 UTC, nglelinh commented
> Most translations get loaded, except for a couple and I couldn't find out why. @nglelinh would you mind having a look? Here's a screenshot. _Show 2 matches_ should be translated as well, but isn't.
> ![image](https://user-images.githubusercontent.com/2384578/100914124-eda93d00-34d2-11eb-995f-d9cdca8b6eef.png)
> 
> In addition to that, I don't think the code to load the user defined translations is correct. Would you please try out this?
> 
> ```diff
> --- a/plugin.php
> +++ b/plugin.php
> @@ -108,15 +108,16 @@ add_action('admin_init', [$pAdminViewController, 'add_ajax_actions']);
>  add_action('admin_init', [CaptchaDataChecker::class, 'addHook']);
> 
>  add_action('plugins_loaded', function() {
> -       load_plugin_textdomain('onoffice', false, basename(ONOFFICE_PLUGIN_DIR).'/languages');
> -       load_plugin_textdomain('onoffice-for-wp-websites', false, basename(ONOFFICE_PLUGIN_DIR) . '/languages');
> +       load_plugin_textdomain('onoffice-for-wp-websites', false, basename(ONOFFICE_PLUGIN_DIR) . '/languages/onoffice-for-wp-websites');
> +       // Check 'onoffice-personalized' Folder exists
> +       $onofficePersonalizedFolder = plugin_dir_path(__DIR__) . 'onoffice-personalized/languages';
> +       if (is_dir($onofficePersonalizedFolder)) {
> +               load_plugin_textdomain('onoffice', false, $onofficePersonalizedFolder);
> +       } else {
> +               load_plugin_textdomain('onoffice', false, basename(ONOFFICE_PLUGIN_DIR).'/languages');
> +       }
>  });
> 
> -// Check 'onoffice-personalized' Folder exists
> -$onofficePersonalizedFolder = plugin_dir_path(__DIR__) . 'onoffice-personalized';
> -if (is_dir($onofficePersonalizedFolder)) {
> -       load_plugin_textdomain('onoffice', false, basename(ONOFFICE_PLUGIN_DIR) . '/languages');
> -}
> 
>  // "Settings" link in plugins list
>  add_filter('plugin_action_links_'.plugin_basename(__FILE__), [$pAdminViewController, 'pluginSettingsLink']);
> ```

@jayay it was about caching on the browser, we retested and see it's working
we also made some fixings on the loading text domain from "onoffice-personalized/languages", please help to recheck again

2020-12-03 10:22 UTC, jayay commented
Translations for the German language are now being loaded from the WP platform. It's good to know this works before the changes are even released. This basically means, the plugin doesn't need to ship with the `languages/onoffice-for-wp-websites-de_DE.{po,mo}` files. That's something to care about later, though.

2020-12-03 15:21 UTC, jayay approved these changes

2020-12-17 11:09 UTC, merged