8300 configuration mask select contact form
onOfficeGmbH/oo-wp-plugin pull request #36
Opened 2020-12-10 03:12 UTC by hungnc89

configuration mask select contact form

2020-12-23 11:05 UTC, jayay requested changes
Thanks for the work!

Most of it is good, but I'm sure the migration step would break existing sites. Please have a look at my comments and feel free to ask me.
Other than that, I've written a couple of comments right here.

2021-01-07 14:44 UTC, jayay approved these changes
It looks good to me. Unfortunately, we're going to have to wait for #29 to be merged first because `DatabaseChanges.php` will conflict.

2021-01-07 14:44 UTC, jayay commented on plugin/EstateDetail.php
> +	 * @return array Returns an string
The method can be shortened all the way:

```php
<?php
public function getShortCodeForm(): string
{
	return  '[oo_form form="' . $this->getDataView()->getShortCodeForm(). '"]';
}
```

2021-01-07 14:44 UTC, jayay commented on plugin/Installer/DatabaseChanges.php
> +	private function installDataQueryFormFieldConfig($defaultFormId)
A type hint would be nice

2021-04-15 13:43 UTC, jayay commented
@hungnc89 Would you please rebase this on top of master? This is going to be released soon

2021-04-20 10:25 UTC, jayay commented
I made a new branch for the fixes, it is [8300-configuration-mask-select-contact-form-2](/onOfficeGmbH/oo-wp-plugin/tree/8300-configuration-mask-select-contact-form-2). However, there is a risky test (it has been there before, but our unit test configuration changed), which makes the tests fail. Would you please have a look?

2021-04-20 11:05 UTC, hungnc89 commented
> I made a new branch for the fixes, it is [8300-configuration-mask-select-contact-form-2](/onOfficeGmbH/oo-wp-plugin/tree/8300-configuration-mask-select-contact-form-2). However, there is a risky test (it has been there before, but our unit test configuration changed), which makes the tests fail. Would you please have a look?

2021-04-20 12:23 UTC, jayay commented
Thank you!

2021-05-25 14:14 UTC, merged