Filter sold and reserved estates from similar estates.
onOfficeGmbH/oo-wp-plugin pull request #43
Opened 2021-01-18 10:39 UTC by FD-Websolutions

2021-01-21 07:39 UTC, jayay requested changes
I don't know if you've talked to Pawel about this, but it makes sense to me. Would you mind removing the `.DS_Store` files, please?

2021-01-21 07:39 UTC, jayay commented on plugin/Filter/DefaultFilterBuilderSimilarEstates.php
> +		$filter['reserviert'] []= ['op' => 'not in', 'val' => 1];
Why not insert it at the top? (line 63)

2021-01-21 08:08 UTC, FD-Websolutions commented on plugin/Filter/DefaultFilterBuilderSimilarEstates.php
> +		$filter['reserviert'] []= ['op' => 'not in', 'val' => 1];
I changed the position.

2021-01-27 07:39 UTC, jayay approved these changes

2021-02-01 09:24 UTC, merged

2021-02-01 11:00 UTC, jayay commented
Released in v2.8.3.