9409- hide multiparkingLot field
onOfficeGmbH/oo-wp-plugin pull request #44
Opened 2021-01-22 07:18 UTC by hungnc89

2021-01-26 16:54 UTC, jayay requested changes
This is quite good.

The only thing that I would ask you to change is the setter for the container. See comments below.

2021-01-26 16:54 UTC, jayay commented on plugin/Renderer/InputFieldCheckboxRenderer.php
> +		if (empty($this->_pContainer)) {
Building the container should be done in constructor, so that `if (empty())` can be removed

2021-01-26 16:54 UTC, jayay commented on plugin/Renderer/InputFieldCheckboxRenderer.php
> +		$this->_pContainer = $pContainer;
The setter should be removed

2021-01-26 16:54 UTC, jayay commented on plugin/Renderer/InputFieldCheckboxRenderer.php
> +		$this->_pContainer = $pContainer;
I see this is hard. Could this be accomplished by making the container an optional constructor argument?

2021-01-26 16:54 UTC, jayay commented on tests/TestClassInputFieldCheckboxRenderer.php
> +	public function testRenderMultiParkingLotField()
I like this test, do you think it is possible to test a 'regular' field as well?

2021-01-27 17:24 UTC, jayay requested changes

2021-01-27 17:24 UTC, jayay commented on plugin/Renderer/InputFieldCheckboxRenderer.php
> +		if (empty($_pContainer)) {
Could you please turn `empty` into `!== null`? I would appreciate if `$_pContainer` would get a type hint.

2021-01-27 17:24 UTC, jayay commented on plugin/Renderer/InputFieldRenderer.php
> +	public function __construct($type, $name, $value = null, $_pContainer = null)
This doesn't seem to be used. Is this on purpose?

2021-01-28 13:40 UTC, jayay approved these changes

2021-07-20 13:26 UTC, jayay commented
Could the code maybe be simplified by rewriting it to work in the same way as #90?

2021-08-05 09:01 UTC, michaelarnold-dev commented
@vu-vuong-esg Could you please resolve the conflict?

2021-08-05 09:27 UTC, vu-vuong-esg commented
> @vu-vuong-esg Could you please resolve the conflicts?

Sure

2021-08-05 09:45 UTC, vu-vuong-esg commented
> @vu-vuong-esg Could you please resolve the conflicts?

I resolved it

2021-08-24 08:44 UTC, closed without merging

2021-08-24 08:45 UTC, michaelarnold-dev commented
will be substituted by another, newer project.