11300-radius-not-work-similar-estate
onOfficeGmbH/oo-wp-plugin pull request #79
Opened 2021-05-04 09:13 UTC by hungnc89

2021-05-04 11:46 UTC, jayay commented
Looks good. Any change this can be tested?

2021-05-12 14:35 UTC, jayay requested changes
Changing the signature of `\onOffice\WPlugin\EstateDetail::getSimilarEstates` might break the templates

2021-05-12 14:35 UTC, jayay commented on plugin/EstateDetail.php
> +	public function getSimilarEstates($pContainer): string
This would break since it is being called in the `default_detail` template.

2021-05-21 08:10 UTC, jayay commented on plugin/EstateDetail.php
> +	public function getSimilarEstates($pContainer): string
It could be an optional parameter

2021-07-19 13:12 UTC, jayay commented
Is there any news on this?

2021-07-20 02:11 UTC, nglelinh commented
The discussion about this PR is here https://github.com/orgs/onOfficeGmbH/teams/oo-wp/discussions/16
We mentioned that with current structure we could not write unittest for the feature. @jayay  Could you please consider again?

2021-07-21 10:01 UTC, jayay approved these changes

2021-08-24 07:08 UTC, merged