13806 make contact selectable
onOfficeGmbH/oo-wp-plugin pull request #88
Opened 2021-06-24 05:00 UTC by hungnc89

2021-07-26 15:31 UTC, jayay commented
Thanks! Is it possible to cover more lines with tests?

2021-07-30 08:59 UTC, hungnc89 commented
Hi @jayay,
I added tests for code.
Thanks

2021-07-30 09:09 UTC, jayay commented
@hungnc89 Thank you so much! The test is broken, would you please have a look?

2021-07-30 09:25 UTC, hungnc89 commented
@jayay oh sorry. I fixed it

2021-08-02 09:02 UTC, jayay approved these changes
Thank you!

2021-11-02 15:21 UTC, jayay requested changes

2021-11-02 15:21 UTC, jayay commented on plugin/Model/FormModelBuilder/FormModelBuilderDBForm.php
> +			var_dump($fields['ArtDaten']);
This looks like debug output

2021-11-03 02:17 UTC, hungnc89 commented
@jayay sorry. I fixed it

2021-12-03 17:02 UTC, jayay requested changes
There's still a comment of mine, that's not resolved.

2021-12-03 17:05 UTC, jayay commented on plugin/Installer/DatabaseChanges.php
> +		return "CREATE TABLE $tableName (
The new column literally needs to be added in the method `getCreateQueryForms`.

2021-12-06 03:24 UTC, tung-le-esg commented
> There's still a comment of mine, that's not resolved.

@hoangdoegs Could you please check the comments and resolve the conflict file?

2021-12-09 15:06 UTC, jayay approved these changes

2022-01-04 11:50 UTC, michaelarnold-dev commented
@hungnc89 Could you please improve the code coverage?

2022-01-10 09:21 UTC, hoangdoegs commented
> @hungnc89 Could you please improve the code coverage?

I added more tests. Now the coverage has been improved

2022-01-10 17:22 UTC, jayay approved these changes

2022-01-26 13:07 UTC, michaelarnold-dev commented
Comment of Robert Igelmund Requirement: 

"The user can theoretically set the contact type in the scheduled field in "Form Specific Options" (FO) as well as add it to the "Fields" list (FL) so that it is selectable in the frontend form. This may cause a conflict. This case will probably rarely occur in practice. If there is a conflict, the intended field should win in the FO unless no contact type is selected."

The mail to the broker contains in case of conflict the wrong contact type, namely the one selected by the user in the frontend.
The mail should list the contact type that is also written in the address.

That means the error from #2752693 is not fixed with version 2.21.0-27-g8d09228b. See also screenshot.

2022-01-27 03:15 UTC, nglelinh commented
@jayay please help to confirm that the last feedback from Robert is not the WP issue

2022-01-31 13:06 UTC, jayay commented
@nglelinh The screenshot appears to be correct, but sadly, is in German. It depicts the field _kind of contact_ in the e-mail to be different than the _kind of contact_ of the newly created address, which is the behavior @michaelarnold-dev is referring to here: https://github.com/onOfficeGmbH/oo-wp-plugin/pull/88#issuecomment-1022180401.

2022-02-08 07:04 UTC, hoangdoegs commented
@jayay Please check again

2022-02-17 14:08 UTC, jayay approved these changes

2022-03-04 16:12 UTC, jayay approved these changes

2022-03-08 08:05 UTC, merged